export const API_ERROR_MESSAGES: Record<string, string> = {
  ERR_001_VALIDATE_ERROR: '',
  ERR_002_PERMISSION_DENIED: 'Bạn không có quyền truy cập vào tài nguyên này!',
  ERR_003_AUTHENTICATION_FAILED: 'Số điện thoại hoặc mật khẩu không đúng!',
  ERR_004_NOT_AUTHENTICATED: 'Bạn phải đăng nhập để truy cập tài nguyên này!',
  ERR_404_NOT_FOUND: 'Không tìm thấy tài nguyên yêu cầu!',
  ERR_500_INTERNAL_SERVER_ERROR:
    'Đã xảy ra lỗi không mong muốn. Vui lòng thử lại sau!',
};

export const VALIDATE_ERROR_MESSAGES: Record<string, string> = {
  REQUIRED: 'Trường này là bắt buộc!',
  EMPTY_PHONE_NUMBER: 'Vui lòng nhập số điện thoại!',
  EMPTY_EMAIL: 'Vui lòng nhập email!',
  INVALID_EMAIL: 'Email không hợp lệ!',
  EMPTY_USERNAME: 'Vui lòng nhập tên đăng nhập!',
  MIN_USERNAME_LENGTH: 'Tên đăng nhập phải có ít nhất 5 ký tự!',
  MAX_USERNAME_LENGTH: 'Tên đăng nhập không được vượt quá 100 ký tự!',
  EMPTY_PASSWORD: 'Vui lòng nhập mật khẩu!',
  EMPTY_CONFIRM_PASSWORD: 'Vui lòng nhập xác nhận mật khẩu!',
  PASSWORD_MIN_LENGTH: 'Mật khẩu phải có ít nhất 8 ký tự!',
  EMPTY_OTP: 'Vui lòng nhập mã OTP!',
  INVALID_OTP: 'Mã OTP không hợp lệ!',
  EMPTY_NEW_PASSWORD: 'Vui lòng nhập mật khẩu mới!',
  NEW_PASSWORD_MIN_LENGTH: 'Mật khẩu mới phải có ít nhất 8 ký tự!',
  INVALID_PHONE_NUMBER: 'Số điện thoại không hợp lệ!',
  PASSWORD_MISMATCH: 'Mật khẩu không khớp!',
  EMPTY_NAME: 'Vui lòng nhập tên!',
  EMPTY_LAST_NAME: 'Vui lòng nhập họ!',
  INVALID_NAME: 'Tên không hợp lệ!',
  INVALID_LAST_NAME: 'Họ không hợp lệ!',
  // Badge validation
  EMPTY_BADGE_NAME: 'Vui lòng nhập tên huy hiệu!',
  MIN_BADGE_NAME_LENGTH: 'Tên huy hiệu phải có ít nhất 3 ký tự!',
  MAX_BADGE_NAME_LENGTH: 'Tên huy hiệu không được vượt quá 100 ký tự!',
  EMPTY_POINT_TO_GET: 'Vui lòng nhập số điểm cần đạt!',
  INVALID_POINT_TO_GET: 'Số điểm phải là số nguyên dương!',
  MIN_POINT_TO_GET: 'Số điểm phải lớn hơn 0!',
  EMPTY_ICON_URL: 'Vui lòng nhập URL biểu tượng!',
  INVALID_ICON_URL: 'URL biểu tượng không hợp lệ!',
  EMPTY_DESCRIPTION: 'Vui lòng nhập mô tả!',
  MIN_DESCRIPTION_LENGTH: 'Mô tả phải có ít nhất 10 ký tự!',
  MAX_DESCRIPTION_LENGTH: 'Mô tả không được vượt quá 500 ký tự!',
  // Dietary Preference validation
  EMPTY_DIETARY_NAME: 'Vui lòng nhập tên chế độ ăn!',
  MIN_DIETARY_NAME_LENGTH: 'Tên chế độ ăn phải có ít nhất 3 ký tự!',
  MAX_DIETARY_NAME_LENGTH: 'Tên chế độ ăn không được vượt quá 100 ký tự!',
  EMPTY_DIETARY_DESCRIPTION: 'Vui lòng nhập mô tả chế độ ăn!',
  MIN_DIETARY_DESCRIPTION_LENGTH: 'Mô tả chế độ ăn phải có ít nhất 10 ký tự!',
  MAX_DIETARY_DESCRIPTION_LENGTH:
    'Mô tả chế độ ăn không được vượt quá 500 ký tự!',
};
